### ISSUE TITLE
[stats] PCA

### ISSUE THREAD

**Issue by jhk0530** [statgarten/door#18]

**Comment by jhk0530** [comment]
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/6457691/186135710-a123ab57-cb1e-424c-bfcf-094f043f659d.png">

flow: 
- Example data `scholarship`
- update data (`학제별`, `설립별`) to `factor`
- goto `stat` panel
- select columns:  
- "교외장학금.국가" "교외장학금.지방자치단체" "교외장학금.사설및기타" 
- "교내장학금.성적우수장학금" "교내장학금.저소득층장학금" "교내장학금.근로장학금" "교내장학금.재난장학금"     "교내장학금.교직원장학금"   "교내장학금.기타"
- check scale = `TRUE`
- **draw**

**Comment by jinseob2kim** [comment]
Good
