### ISSUE TITLE
[etc] hex sticker design issue

### ISSUE THREAD

**Issue by YoungjunNa** [statgarten/door#34]
door의 hex sticker 디자인을 해보려고 하는데요.
패키지에 대한 간단한 소개 + 이름을 지은 목적에 대해서 reply 해주시면 참고해 보도록 하겠습니다.

**Comment by jhk0530** [comment]
데이터 분석 작업을 일괄적으로 할 수 있는 shiny one app 목적으로 만든 패키지입니다.
다른 package / module을 사용할 수 있게 하는 관점에서 `door`라고 지었어요 (windows 느낌)

**Comment by YoungjunNa** [comment]
고맙습니다! 잘 만들어 볼게요!
