### ISSUE TITLE
Crash at Update Data

### ISSUE THREAD

**Issue by ChangwooLim** [statgarten/door#39]
Error message: 
Warning: Error in cor: 'x' must be numeric
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>

Data:
datatoys::bloodTest

Situation:
Load bloodTest Data(Normal)->
Click Update Data(Normal)->
Change SEX, AGE_G, ANE, IHD, STK to Factor and Click Apply Changes(Abnormal)

**Comment by jhk0530** [comment]
`board`가 0.0.2 버전이 맞는지 확인해주세요

**Comment by ChangwooLim** [comment]
Solved after re-install every related package(door, scissor, etc)
