### ISSUE TITLE
Error at Drawing PCA plot

### ISSUE THREAD

**Issue by ChangwooLim** [statgarten/door#43]
Error message:
'names' attribute [2] must be the same length as the vector [1]

Data:
datatoys::bloodTest(Customized)

Situation:
Load bloodTest Data->
Click Update Data->
Change SEX, ANE, IHD, STK to Factor and Click Apply Changes->
Go to Stat->
Go to PCA tab->
Set:
  PCA columns (Numeric): TCHOL
  Group columns (Factor): SEX
  Other options: as default
->
Click 'draw'

<img width="1446" alt="스크린샷 2022-10-01 오후 9 36 30" src="https://user-images.githubusercontent.com/86377226/193409954-c3177dd3-b9f3-4621-bc5c-9ea8adbb764d.png">

**Comment by jhk0530** [comment]
PCA must include more than 2 column.

**Comment by jhk0530** [comment]
<img width="498" src="https://user-images.githubusercontent.com/6457691/193740593-8ec247a4-1791-4282-b629-1289b6ec2f9d.png">
