### ISSUE TITLE
패키지 설치 dependency 이슈

### ISSUE THREAD

**Issue by YoungjunNa** [statgarten/door#44]
패키지 설치시 Github에서 hosting 되는  Statgarten 패키지들 (board, colorpen, datatoys, stove, soroban 등) 설치가 불가능한데, 이 부분 이슈 해결이 필요해 보입니다.

일단 README에 땜빵식으로 패키지 설치 전에 의존성 있는 패키지들을 수동으로 설치 가능하게 제시하는 방법은 어떨까요?
`remotes::install_github(c("statgarten/board", "statgarten/colorpen", "statgarten/datatoys", "statgarten/stove"))`

**Comment by ChangwooLim** [comment]
init()이라는 함수 만들어서 statgarten::init()이나 door::init() 이렇게 실행하면 설치되게 하는것도 괜찮을 것 같습니다.

**Comment by ChangwooLim** [comment]
Pull Request 하였습니다.

**Comment by YoungjunNa** [comment]
오잉, 제가 잘 모르는 내용이긴 한데..
DESCRIPTION 파일 내에 Remotes: 를 지정하면 패키지 인스톨 시 자동으로 저장소를 잡아주나요? 만약 그렇다면 `github::statgarten/soroban` 이 누락된 것으로 보입니다!!
