### ISSUE TITLE
[ETC] PCA기능개선

### ISSUE THREAD

**Issue by ChangwooLim** [statgarten/door#70]
# Summary (in one line)
Stat의 PCA시 2개 이상의 PCA Column이 필요하나, 아래 스크린샷으로는 해당 사실을 파악하기 힘들어 텍스트로 설명되었으면 합니다.
# Why this issue?

# What will this issue solve

# How to solve this issue (Optional)

<img width="1442" alt="스크린샷 2023-08-03 오전 9 58 16" src="https://github.com/statgarten/door/assets/86377226/e206e6c4-8119-4562-ac66-c15db71ce819">

**Comment by jhk0530** [comment]
moved to soroban
