### ISSUE TITLE
[BUG] Regression Tree Error

### ISSUE THREAD

**Issue by ChangwooLim** [statgarten/door#71]
**Describe the bug**

Warning in min(pred_data) :
  no non-missing arguments to min; returning Inf
Warning in max(pred_data) :
  no non-missing arguments to max; returning -Inf
Warning: Error in geom_node_plot: Problem while converting geom to grob.
ℹ Error occurred in the 3rd layer.
Caused by error in `seq.default()`:
! 'from' must be a finite number
  206: <Anonymous>
  205: signalCondition
  204: signal_abort
  203: rlang::abort
  202: cli::cli_abort
  201: handlers[[1L]]
  200: h
  199: .handleSimpleError
  198: stop
  197: seq.default
  194: predict_data
  193: draw_panel
  192: self$draw_panel
  190: FUN
  189: lapply
  188: draw_layer
  187: self$geom$draw_layer
  186: draw_geom
  185: l$draw_geom
  184: f
  177: by_layer
  176: ggplot_gtable.ggplot_built
  174: print.ggplot
  169: func
  167: f
  166: Reduce
  157: do
  156: hybrid_chain
  128: drawPlot
  114: <reactive:plotObj>
   98: drawReactive
   85: renderFunc
   84: output$treeModule_1-plot
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.

<img width="1495" alt="스크린샷 2023-08-03 오전 10 01 14" src="https://github.com/statgarten/door/assets/86377226/8cce5c77-5d1c-4515-898e-9322e781a424">

데이터는 example_g1e.xlsx
Node, Edge, Terminal은 기본값, VA_LT, VA_RT는 Factor로 변환하였습니다(0, 1로 binarize)

**Comment by jhk0530** [comment]
moved to soroban
