### ISSUE TITLE
[BUG] Linear Regression Error

### ISSUE THREAD

**Issue by ChangwooLim** [statgarten/door#72]
**Describe the bug**

1. 어떠한 경우라도 그래프가 나타나지 않음.
2. x에 numeric, y에 factor 입력시 에러메시지와 함께 프로그램 crash

Warning in model.response(mf, "numeric") :
  using type = "numeric" with a factor response will be ignored
Warning in Ops.factor(y, z$residuals) : ‘-’ not meaningful for factors
Warning in Ops.factor(weighted.residuals(object), 2) :
  ‘^’ not meaningful for factors
Warning: Error in step: AIC is -infinity for this model, so 'step' cannot proceed
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>

**To Reproduce**
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jhk0530** [comment]
<img width="1793" alt="스크린샷 2023-08-03 오후 5 02 29" src="https://github.com/statgarten/door/assets/6457691/2f947430-1b23-4849-affa-998173745d82">

Linear regression 은 target이 numeric 입니다. (factor 는 logistic regression으로 지원하지 않음)
