### ISSUE TITLE
[BUG] K-means Clustering Error

### ISSUE THREAD

**Issue by ChangwooLim** [statgarten/door#73]
**Describe the bug**

Labels-Opt 가 NULL이 아닐 경우 에러 발생

<img width="1468" alt="스크린샷 2023-08-03 오전 10 13 30" src="https://github.com/statgarten/door/assets/86377226/3b0856b9-ad1a-4238-9705-286968618e6a">

**Comment by jhk0530** [comment]
Issue moved to soroban.
