### ISSUE TITLE
[BUG] Datatoys does not work at Windows

### ISSUE THREAD

**Issue by ChangwooLim** [statgarten/door#91]
1. install_github("statgarten/statgarten")으로 설치
2. door::run_app()으로 실행
3. datatoys 탭에서 데이터 불러올 시 Crash

원인: 다운로드 받는 데이터를 /tmp 경로에 저장

해결방법: 상대 경로로, 현재 report와 같이 패키지 폴더에서 처리하면 해결 될 것으로 예상됩니다.

**Comment by jhk0530** [comment]
`tempfile`을 사용하여 수정. windows 작동 확인
