### ISSUE TITLE
[BUG] Linear Regression 에러 메시지 추가

### ISSUE THREAD

**Issue by ChangwooLim** [statgarten/door#94]
<img width="380" alt="스크린샷 2023-11-14 오후 9 06 15" src="https://github.com/statgarten/door/assets/86377226/fe304b71-7e45-4252-b511-96ae94a76081">

Linear Regression시, y값에 species가 들어가면 안 됨에도 불구하고 입력시 에러 발생이 아닌, 프로그램이 강제 종료됩니다.

**Comment by jhk0530** [comment]
issue moved to [soroban](https://github.com/statgarten/soroban/issues/13)
