### ISSUE TITLE
[BUG] kernlab 패키지 Dependency 추가 필요

### ISSUE THREAD

**Issue by ChangwooLim** [statgarten/door#98]
ML-Classification-SVM linear algorithm 실행 시 아래와 같은 오류가 발생합니다.

Warning: Error in check_installs: Some package installs are required: 
• 'kernlab', 'kernlab'
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>

Dependency 추가로 간단히 해결 가능하리라 생각됩니다.

**Comment by jhk0530** [comment]
duplicated issue in [stove](https://github.com/statgarten/stove/issues/27)
