### ISSUE TITLE
[BUG] ML탭 Hyperparameter Options 지정 불가능

### ISSUE THREAD

**Issue by ChangwooLim** [statgarten/door#99]
<img width="459" alt="스크린샷 2023-11-14 오후 10 11 35" src="https://github.com/statgarten/door/assets/86377226/8e4f6bfd-ef79-4980-9977-22a09b2429b4">
위 스크린샷에서, metric을 rmse로 변경하여 저장해야 Regression이 가능한데, 저장이 불가합니다.

**Comment by jhk0530** [comment]
![image1](https://github.com/statgarten/door/assets/6457691/29a362e9-0699-4dc9-9bf0-cf3b760d9f0e)
![image2](https://github.com/statgarten/door/assets/6457691/1520d107-fd50-4df3-9c1f-fd5b74d28a7d)
